### ISSUE TITLE
feat: Use zfp compression for fields

### ISSUE THREAD

**Issue by macrintr** [ZettaAI/corgie#2]
Consider incorporating [CloudVolume's zfp integration](https://github.com/seung-lab/cloud-volume/pull/549) for displacement fields and float encodings. Might want to track provenance better [CirrusVolume](https://github.com/ZettaAI/cirrus-volume) first, so that we can track the encoding details.

**Comment by william-silversmith** [comment]
+1 just be aware that this is a very experimental deployment first. Let's do some experiments before we put important data in the format (`zfpc`).
